name: HTML Validator

on:
  push  # プッシュされたら実行

jobs:
  test:
    name: Validate HTML
    runs-on: ubuntu-latest

    steps:
      # 1. コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # package.jsonを動かすNode.js
          cache: 'npm'        # npmの依存関係をキャッシュする

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 4. 'npm test' を実行 (package.jsonで定義したコマンド)
      - name: Run HTML validation
        run: npm test
