# .github/workflows/secrets-demo.yml
name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Secretsを参照する基本例
      - name: Use API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Repository Secret
        run: |
          echo "This job can access the secret via \$\{\{ secrets.SECRET_NAME \}\} syntax."
          echo "For example, here we read: \${{ secrets.API_KEY }} (masked in logs)."
          # 実際の値を出力しないようマスク
          echo "::add-mask::${API_KEY}"
          echo "API key length: ${#API_KEY}"
